CREATE TABLE IF NOT EXISTS user_ (
    id_ SERIAL,
    fullname_ VARCHAR(255) NOT NULL,
    email_ VARCHAR(255) UNIQUE NOT NULL,
    password_ VARCHAR(255) NOT NULL,
    created_at_ TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at_ TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    PRIMARY KEY (id_)
);

CREATE OR REPLACE TRIGGER update_user_updated_at
    BEFORE UPDATE ON user_
    FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();